# Sunset_PktConverter Initialization


Sunset_PktConverter/Sunset_Common set usePropagationDelay 0
Sunset_PktConverter/Sunset_Common set useDistance 0
Sunset_PktConverter/Sunset_Common set useProcessingDelay_ 0
Sunset_PktConverter/Sunset_Common set useResponseBit_ 0
Sunset_PktConverter/Sunset_Common set useBackSeat 0

Sunset_PktConverter/Sunset_Common set DELAY_BITS 18
Sunset_PktConverter/Sunset_Common set DISTANCE_BITS 16
